apiVersion: v1
kind: Service
metadata:
  name: mongo-web-service
spec:
  selector:
    app: mongo-web
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30200
