apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-web-deployment
  labels:
    app: mongo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-web
  template:
    metadata:
      labels:
        app: mongo-web
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:latest
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url
